# Generated by Django 5.1.7 on 2025-03-16 04:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

def set_default_creators(apps, schema_editor):
    Project = apps.get_model('projects', 'Project')
    User = apps.get_model(settings.AUTH_USER_MODEL)
    admin = User.objects.filter(is_superuser=True).first()
    Project.objects.filter(created_by__isnull=True).update(created_by=admin)
class Migration(migrations.Migration):
    
    


    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='folderstructure',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='projects.project'),
        ),
    ]
