# Generated by Django 4.2.20 on 2025-07-27 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_remove_project_server_name_alter_project_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
