# Generated by Django 4.2.20 on 2025-07-27 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_project_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='trade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
