# Generated by Django 4.2.20 on 2025-07-27 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_project_trade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='folder_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='trade',
            field=models.CharField(max_length=100),
        ),
    ]
