# Generated by Django 5.1.7 on 2025-03-16 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.UUIDField(unique=True)),
                ('classification', models.CharField(blank=True, max_length=255, null=True)),
                ('predicted_due_date', models.DateField(blank=True, null=True)),
                ('anomalies_detected', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
