# Generated by Django 5.1.7 on 2025-03-16 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StorageLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.UUIDField(unique=True)),
                ('storage_type', models.CharField(choices=[('local', 'Local Server'), ('aws_s3', 'AWS S3'), ('gdrive', 'Google Drive')], max_length=10)),
                ('file_path', models.CharField(max_length=500)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
