# Generated by Django 4.2.20 on 2025-06-22 03:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_alter_document_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='doc_id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=50, unique=True),
        ),
    ]
